# Generated by Django 5.2.4 on 2025-08-04 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                default="profile_images/default-avatar.png",
                null=True,
                upload_to="profile_images/",
            ),
        ),
    ]
