# Generated by Django 5.2.4 on 2025-07-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='toc',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
