# Use postgres/example user/password credentials

services:
  db:
    image: postgres
    restart: always
    # set shared memory limit when using docker compose
    shm_size: 128mb

    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      # on the left is local_host
      # I can give any name on the left
      # on the right is path that is defined
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
